### ISSUE TITLE
New functionality request: Spherical Mirror Projection 

### ISSUE THREAD

**Issue by ImmersiveTheatres** [CelestiaProject/Celestia#572] opened 2019-12-22 07:42 UTC
Hello Celestia development community

I own and operate my own mobile planetarium business and Celestia 1.4.1 (spherical mirror projection version) has for many years been as important to me as Stellarium plus my catalogue of fulldome (360°) films.

In fact, many mobile planetarium operators like me have delighted audiences with Celestia 1.4.1 adapted for spherical mirror projection - immersing them with Celestia in 360°. 

Spherical mirror projection is simply an inexpensive way of projecting in 360°. All you need is a projector, a spherical mirror and 'warping' of digital content so it looks correct on the dome (see diagram [here](http://bit.ly/dd-smp)).

The 1.4.1 spherical mirror version of Celestia was commissioned by mobile planetarium sales company _Discovery Dome_ many years ago and made available free to its customers.

Of course 1.4.1 is very old now and no longer works with the latest operating systems (with OS X anyway, which is what I use). Plus it has always carried a number of bugs.

**It would be wonderful if a spherical mirror projection option was incorporated into the current version of Celestia**. This would make Celestia of great value and interest to the large and growing number of small and medium digital dome operators around the world.

Have you perhaps considered adding spherical mirror projection functionality, like Stellarium has done for many years now?

I'm not a programmer, but would love to help where I can. **Please let me know if any developers would like to see a copy of the 1.4.1 spherical mirror version** (I am a _Discovery Dome_ sales agent, so I am allowed to share this version with you). Perhaps if you create a repository on here I can upload this version for those interested to examine? I have both Mac and Windows versions.

Also, Paul Bourke (the inventor of spherical mirror projection in 2005) is an academic who makes all the information and support you require as regards spherical mirror projection freely available on his website eg http://paulbourke.net/dome/stellarium/ He would be delighted to help you achieve spherical mirror projection in Celestia.

Please let me know if I can help in any other way?

By allowing Celestia to be projected in 360° inside digital planetariums, you will be introducing hundreds of thousands of people (mainly schoolchildren) to the magical universe of Celestia - and then operators like me will encourage these children to download Celestia at home for themselves (as we do with Stellarium). 

Thanks very much.

Mario

**Comment by eyvallah** [comment] 2019-12-22 09:13
I have read the post on the forum, it is really a good idea to me to have it in the future. it would require quite some work as one would reckon.

it would be good if you can share the source code, with me and @375gnu via email, since it'd be more straightforward for us to incorporate existing code.

**Comment by ImmersiveTheatres** [comment] 2019-12-22 21:04
Thank you for your interest in creating a version of Celestia for the dome @eyvallah and @375gnu . Please email me and I will share the warped version 1.4.1 with you: mario@immersive-theatres.com

**Comment by 375gnu** [comment] 2019-12-23 16:57
Hi @ImmersiveTheatres, please contact Discovery Dome and request source codes of their modified Celestia. As Celestia is licenced under terms of GPL2+ they must provide them to their customers. Without them it will be hard to reimplement this function.

**Comment by ImmersiveTheatres** [comment] 2019-12-24 12:20
OK I have contacted Discovery Dome and they don't have the source code, so they referred me to Paul Bourke, who was originally commissioned to do the work. 

Paul Bourke says he does not have the source code either, because he employed a programmer called Evan Hallein to create the dome version of Celestia 1.4.1.

I have managed to contact Even Hallein and he thinks he may no longer have the source code, but he will check when he returns from holiday in two weeks time.

I will follow up with him next month to try and obtain the source code.

**Comment by ImmersiveTheatres** [comment] 2019-12-24 12:25
During my investigation, both Discovery Dome and Paul Bourke were delighted to hear the Celestia development team wishes to incorporate a spherical mirror option for Celestia.

In fact, Paul Bourke said that if we cannot obtain the original 1.4.1 source code: _"...assuming Celestia already creates fisheye, then the warping is pretty straight forward. It is normally the fisheye bit that the harder part."_

Discovery Dome said: _"That would be cool to get Celestia up to date and warped (because WorldWide Telescope isn’t available for Mac). As for the source code ... probably would be better to start from scratch and use external warp meshes so we can go up to 4K, larger domes, etc…"_

**Comment by LafuenteAstronomy** [comment] 2019-12-24 17:25
You know honestly, it feels like we're getting support from official groups once again. That's really good to hear from you, ImmersiveTheaters!

**Comment by SevenSpheres** [comment] 2019-12-24 19:51
> You know honestly, it feels like we're getting support from official groups once again. That's really good to hear from you, ImmersiveTheaters!

Agreed, it really is!

**Comment by ImmersiveTheatres** [comment] 2020-02-21 11:56
GOOD NEWS! I have finally received the spherical mirror projection source code for Celestia ver. 1.4.1.

It can be downloaded here:

https://drive.google.com/open?id=1vpefaI36Paa8APKboBZXEj6zFKJLOMqc

It came with the following comment: _There is a CGShader that does the majority of the work in converting the regular projection to a fisheye projection, and this is enabled by configuring a CFILES environment variable, but I’m sure the developers will be able to work out what is required by looking at the source code._

When the spherical mirror projection version of Celestia is released, it will be nice to include in the credits: Andrew Jameson, Systems & Software Engineer, Centre for Astrophysics & Supercomputing, Swinburne University of Technology

Finally, I'd like to be the first to volunteer to test spherical mirror projection beta versions in my mobile domes! :smile:

Mario

**Comment by levinli303** [comment] 2020-10-02 09:31
@ImmersiveTheatres 
I looked at the source code and tried to port the difference over, here is what I got on my Mac, since I cannot run the dome version (32bit programs don't run on Catalina anymore), so is this what it should be looking like?

https://drive.google.com/file/d/1Eefm9bgTUuuyZ4caFXTV9bJJk7qJxz9Z/view?usp=sharing

**Comment by ImmersiveTheatres** [comment] 2020-10-02 09:42
@levinli303 
Thank you for doing that! Yes, it looks correct in that it appears to be a perfect fisheye / fulldome / 360° projection. So it will look great in a dome through a fisheye lens projector.

Yet we need this fisheye / 360° projection **to be warped for the spherical mirror**. Only then will it work in most portable planetariums (that use affordable spherical mirror projection, not the very expensive fisheye lens projection).

See attached image.

The real-time warping is the challenge :-) 


![Warping](https://user-images.githubusercontent.com/59133199/94909928-cd8ddb00-049b-11eb-9d81-45cbaaf08ed5.jpg)

**Comment by levinli303** [comment] 2020-10-02 09:54
hmm, maybe this part can be done with Quartz Composer? http://paulbourke.net/dome/warppatch/

**Comment by ImmersiveTheatres** [comment] 2020-10-02 10:06
Celestia ver. 1.4.1 was spherical mirror warped (that's the code I managed to obtain above).

Are you saying the current version of Celestia cannot be warped? It would be best for warping to be functional both for Macs and Windows.

**Comment by levinli303** [comment] 2020-10-02 11:25
from what I see in the source code you provided, it does not contain fisheye -> spherical mirror warping.

**Comment by ImmersiveTheatres** [comment] 2020-10-02 11:37
That I don't understand, as I received those files from the university that warped ver 1.4.1 to work with the spherical mirror. If you wish, you can download both the Mac and Win versions of 1.4.1 (warped) [here](https://www.dropbox.com/sh/mtqrr8ypd8jzd9p/AACSO9pfPe8kSpJ89-OLb_VTa?dl=0)

**Comment by levinli303** [comment] 2020-10-02 11:47
warping is not included in this source code, as far as I can tell. since my demo video basically includes all the rendering difference in the code you provided.

**Comment by ImmersiveTheatres** [comment] 2020-10-02 11:59
OK I've written to the developer who supplied the code and will let you know what he says :-)

**Comment by ImmersiveTheatres** [comment] 2020-10-02 13:34
Right, here is his comprehensive reply (which now makes sense I guess - although I have no idea why he didn't tell me this the first time! 😠 )

--------------------------

Hi Mario,

Thanks for your message, Yes, the Celestia developers have done all they could since we never implemented the warping algorithm directly into Celestia. Our solution was to:

1.
Modify Celestia so that it rendered to a fisheye view in the centre of the primary computer display (you have these modifications now).
2.
Develop a completely separate application (which we called ScreenCopy) to perform the warping from the primary display to a secondary display (which ran a projector).
3.
ScreenCopy was a (Mac OSX only) application, built in X-code, that read the rendered OpenGL frame produced by Celestia from the graphics card and then warped it to the fish eye texture.

There are similar, now defunct, descriptions of this approach here: http://paulbourke.net/dome/warppatch. 

It is important to note that ScreenCopy would actually warp any full screen application (e.g. a fisheye movie running in QuickTime, Stellarium or Celestia) from the primary display to the secondary display. When no application was running, it would even be able to “warp” the desktop of the primary computer display. Therefore it was never “linked to” or combined with Celestia in any way. 

We did this so that that we could de-couple the warping function from the fisheye rendering software. This would then allow our ScreenCopy software to “warp” any other 3rd party software that could render a fisheye view without the need for:

1.
Modification of the 3rd party software - saving time, effort and cost.
2.
Ease of maintenance - since the provides of the 3rd party software could update their code without us also needing to do this.
3.
No complaints and arguments regarding modification from the authors of the 3rd party software.

And so the software we developed to do this warping has not been publicly released. I hope this explains the situation clearly - please let me know if you have any further questions.

The techniques employed by ScreenCopy (special hooks into the OpenGL rendering pathways, etc) are no longer available on modern Mac operating systems - similar to Paul Bourke’s other “live warping” software I think.

**If the developers want to add warping into Celestia then they would probably need to develop a new solution for it - either natively (Stellarium did this I think)** or via an external application - obviously separate to Celestia, but perhaps more useful to the community.

Cheers,

Andrew

**Comment by ajameson** [comment] 2020-10-02 13:37
Hi Mario,

Just to be clear - I did advise you of exactly this back in Jan 2020, namely:

> I believe that the version of Celestia you might be referring to is version 1.4.0, which was modified for Fisheye projection, not spherical mirror projection. A completely separate software application was used to warp the fisheye image into spherical mirror image.

**Comment by ImmersiveTheatres** [comment] 2020-10-02 13:40
Yes Andrew, but how come I have two versions of Celestia 1.4.1 (Mac and
Win) - and they run warped for spherical mirror?

Are you saying you guys did not create this ready-to-run spherical mirror
version?

**Comment by ajameson** [comment] 2020-10-02 13:57
I'm not sure - none of our software was ever built or released for Windows, so it would seem that the copy you have came from somehwere else? This was happening back in 2006, so a fair bit of water has passed under the bridge since then. 

We certainly tried integrating the warping software directly into Celestia during the early development and testing, but then that approach was discarded for the separate application warping I described above.

**Comment by ImmersiveTheatres** [comment] 2020-10-02 14:05
My, this is turning out to be quite a mystery! 😃  

Nevertheless thank you for all your help Andrew, and apologies I wrongly assumed you were behind the warped 1.4.1 version. 

OK, back to the drawing board ...  🔎

**Comment by ImmersiveTheatres** [comment] 2020-10-02 14:24
To all Celestia developers: in searching through my emails I've again come across these words of Paul Bourke's: 

_**"But, assuming Celestia already creates fisheye, then the warping is pretty straight forward. It is normally the fisheye bit that the harder part"**_

So now that fisheye projection has been achieved (thanks to @levinli303 and @ajameson), I assume Paul Bourke's website has all the required info on how to implement warping for spherical mirror?

Or can this not be reverse engineered from ver. 1.4.1?

**Comment by levinli303** [comment] 2020-10-02 17:49
<img width="806" alt="image" src="https://user-images.githubusercontent.com/17924287/94953543-4b90c700-051a-11eb-88c8-090eef637e0d.png">

for warping this part is missing, so to tell from the header, this was done by Swinburne University of Technology

<img width="487" alt="image" src="https://user-images.githubusercontent.com/17924287/94953707-93afe980-051a-11eb-8bf3-3a5ac29821d9.png">

and these function implementation too.

**Comment by ImmersiveTheatres** [comment] 2020-10-02 18:02
I might be wrong @levinli303 , but I think what happened was Swinburne University did most of the original work (as described by @ajameson earlier), but did not make their warping method available publicly.

Then someone else took what Swinburne did, and added the spherical mirror warping - without updating the header. It seems they wanted to remain a mystery! 😃

Nevertheless this probably means - as Paul Bourke says above - the spherical mirror warping is not so difficult to implement (I know, I know, I'm not a programmer! 😄  . If you investigate http://paulbourke.net/ you'll see plenty of information on how to create spherical mirror warping code.

**Comment by ajameson** [comment] 2020-10-02 21:59
@levinli303 - that is interesting, but I'm still not sure sure where those methods in CelestiaCore are from - they are not in the source code I have available that I provided to Mario. Perhaps you are dumping the binary objects from the compiled version Mario has? I wonder if his version was from the initial developement work we did with Celestia before the ScreenCopy approach was developed? I cannot be sure. 

Regardess, the one remaining copy of the fisheye Celestia source code I have does not have any of these methods in it, so I'm  not really able to help you here on this implementation.

**Comment by levinli303** [comment] 2020-10-03 14:05
@ImmersiveTheatres  I implemented warping, you should be able to see the result here

https://drive.google.com/file/d/1vcAYXfG5y8JkRBNziudzxylePAqJOXUc/view?usp=sharing

**Comment by ImmersiveTheatres** [comment] 2020-10-03 14:08
WOW @levinli303 , that looks correct to me!! 😃  I will be in a dome next Friday, so I'd love to check it in the dome then if possible? Are you able to prepare a version for me to test?

This looks amazing, well done!! 🥳

**Comment by levinli303** [comment] 2020-10-03 15:54
well this is implemented in celestia itself. so it will run on all platforms, including mobile platforms. I only got the rendering part working, warped mouse control is not there yet.

**Comment by levinli303** [comment] 2020-10-04 09:59
@ImmersiveTheatres 
You can download this build to try out, should be fairly unstable. Since dome configuration might be different, you would need a mesh for the warping parameters. I used the one in the 1.4.1 version you provided as default (warp_xyuv.data). If you have a mesh file, you can replace the file in Celestia.app/Resources/CelestiaResources/warp/warp.map.

https://drive.google.com/file/d/1txLbdNG0Lhwk9wyOV8Se3EfF2X94FdjW/view?usp=sharing

for the mesh file format, see:
http://paulbourke.net/dome/meshmapper/ or http://paulbourke.net/dataformats/meshwarp/

**Comment by ImmersiveTheatres** [comment] 2020-10-05 08:10
Thank you for this, I'll download it and try it out tomorrow! 😊

**Comment by ImmersiveTheatres** [comment] 2020-10-07 10:35
@levinli303 THIS IS BRILLIANT! 😃

I'll have a chance to try it in the dome on the weekend, but the 1.4.1 warp mesh is looking fine on my laptop.

What would be REALLY useful is the **Mac keyboard shortcuts**. I've looked online but I can't find anything recent.

In particular I need the Mac shortcut to enter Full Screen please. This way I can use Keyboard Maestro to automate the launch process fully, and have Celestia open correctly in my secondary screen (the dome).

I'm no programmer, but am just curious: did you make the breakthrough by using the 1.4.1 code?

It's all looking so promising - I think we're practically there!!  🥳

**Comment by levinli303** [comment] 2020-10-07 14:10
hmmm, I accidentally removed some of the default menu items, and that prevented some shortcuts. will add back toggle full screen and close window.

the version I provided has a small fov though, so it might behave strangely in many cases. This is done by looking at the code for the fisheye part. for the warping, I referred to the Paul's website mostly (and some decompilation from the binary...)

**Comment by ImmersiveTheatres** [comment] 2020-10-12 11:20
GREAT NEWS! I tested the warped Celestia in a dome on the weekend and it's looking great to me 😃  Thank you for doing this.

I'm keen to put it through its paces to see if there are any bugs / issues - but **I'm limited by the fact I don't have the latest Mac keyboard shortcuts**. I can't seem to find them anywhere online. Do you have a link perhaps?

Thanks very much

**Comment by levinli303** [comment] 2020-10-12 12:46
I think this https://github.com/CelestiaProject/Celestia/blob/master/controls.txt is for keyboard shortcuts.

**Comment by ImmersiveTheatres** [comment] 2020-10-15 12:14
OK it looks like all the MAC keyboard commands are still the same, but one very important one is missing: **Enter Full Screen**

It used to be: Cmnd+F

**Comment by levinli303** [comment] 2020-10-16 04:35
> OK it looks like all the MAC keyboard commands are still the same, but one very important one is missing: **Enter Full Screen**
> 
> It used to be: Cmnd+F

I added back now in this commit. https://github.com/levinli303/CelestiaApp/commit/8a103d0a93a6721d1655ee0ea799baf4ac905bce

**Comment by ImmersiveTheatres** [comment] 2020-10-16 07:26
Thanks - what does that mean though? That it will be included in the next release? Or is it possible to download the new version now?

**Comment by levinli303** [comment] 2020-10-16 07:34
If you mean public release as a new version, this will be include in the next App Store release. But as the fisheye implementation is still a work in progress, next App Store release would not include fisheye.

**Comment by ImmersiveTheatres** [comment] 2020-10-16 07:40
OK what I mean is : can I download a version with the Enter Full Screen
keyboard command for MAC now - so that I can start using it in my
planetarium shows?

**Comment by levinli303** [comment] 2020-10-16 07:43
if you need a version with it, I can compile one with it enabled.

**Comment by ImmersiveTheatres** [comment] 2020-10-16 07:46
Yes please! :-)

**Comment by levinli303** [comment] 2020-10-16 08:31
here it is, the fullscreen shortcut as for any other window on Mac, command + control + F
 https://drive.google.com/file/d/11qzDMotYqPh8SjeJCuwWHF9r31Mrdd_c/view?usp=sharing

**Comment by ImmersiveTheatres** [comment] 2020-10-16 09:06
FABULOUS! Thank you :-) 

A question and one more request please:

- where is the best place to find high resolution textures for this version (and are there instructions somewhere on how to introduce / include the new textures)?

- I keep mistakenly hitting the *Fn + Down Arrow*  [intending to hit the Fn + Left / Right Arrow] - and the planet completely disappears ... and I need to locate it again. Is it possible to disable *Fn + Down Arrow*?

Fn + Up Arrow is disabled.

So I'm wondering if it's possible to disable Fn + Down Arrow too?

Thanks very much

**Comment by levinli303** [comment] 2020-10-16 09:10
I think the Wiki covers a lot of customization https://en.wikibooks.org/wiki/Celestia

on my MacBook, pressing Fn+Down does not do anything.

**Comment by ImmersiveTheatres** [comment] 2020-10-16 09:12
Thanks for the link.

On your MacBook, try giving the planet some rotation and then press Fn+Down ...

**Comment by levinli303** [comment] 2020-10-16 09:22
I think this is by design, Fn+Down equals page down on extended keyboards, which trigger the back in history menu. avoid hitting it if you don't want this behavior.

**Comment by ImmersiveTheatres** [comment] 2020-10-16 13:59
One thing I've just noticed is this version is not removing the Venus clouds to show the surface ie. the **I** key is not removing the clouds, the way it does for Earth.

**Comment by ImmersiveTheatres** [comment] 2020-10-16 14:04
Also: **9 + G** takes us to Pallas - not Pluto (?). Is that intentional?

**Comment by levinli303** [comment] 2020-10-16 14:17
'i' disable cloud map rendering, probably Venus does not have a cloud map at all. and the 9th planet is not Pluto any more. clicking 9 will just select the ninth in the database, it happens to be Pallas. all intentional.

**Comment by ImmersiveTheatres** [comment] 2020-10-16 15:31
I would suggest the Venus clouds are returned to what Celestia used to have ie. if you look at the texture folders, there are both surface textures and cloud textures for Venus. As an astronomy educator, I strongly encourage you to keep this functionality in, because it is a wonderful teaching tool (greenhouse effect, climate change, etc, etc).

An equally critical function for education purposes is to keep Pluto at **G + 9**. Pluto continues to play a major role in the teaching of the Solar System - because the very fact it has been designated a dwarf planet is an opportunity to teach how science is always progressing and improving our understanding of the Universe.

At any rate, it doesn't make sense to have Pallas at number 9 just because it is ninth in the database. Is Mercury first in the database and is Saturn sixth in the database? The reasoning is not consistent. 

I think you'll find most astronomy educators around the world will agree with my suggestions above.

Thank you for all your hard work in support of astronomy education via the excellent teaching tool of Celestia! :-)

**Comment by SevenSpheres** [comment] 2020-10-16 22:06
> One thing I've just noticed is this version is not removing the Venus clouds to show the surface ie. the **I** key is not removing the clouds, the way it does for Earth.
> Also: **9 + G** takes us to Pallas - not Pluto (?). Is that intentional?

This should be fixed in [this PR to CelestiaContent](https://github.com/CelestiaProject/CelestiaContent/pull/27), but I've never finished it...

**Closed** 2020-11-20 15:52 UTC
Labels: enhancement, help wanted

**Comment by dpentecost** [comment] 2022-03-23 03:11
Picking up this thread in 2022 - The Google Drive files from levinli303 are no longer on Drive, and I also need a spherical mirror solution. Does anyone have a working version of this that they can share?  If so, please contact me at dave.pentecost@gmail.com 

Thanks!

**Comment by levinli303** [comment] 2022-03-23 03:32
@dpentecost this is already merged to mainline Celestia. download it from App Store, then read and change the last few lines in celestia.cfg inside the app (you might need to duplicate celestia.cfg in another place)

**Comment by dpentecost** [comment] 2022-03-23 05:17
Thanks for the quick reply and the tip.

**Comment by ImmersiveTheatres** [comment] 2022-03-24 16:19
May I ask for clarification please: the latest version for Mac is 1.6.2 - but it does not appear to be warped for fisheye?

I've added the following three lines to the end of celestia.cfg, and it makes no difference? 

ProjectionMode  "fisheye"
ViewportEffect  "warpmesh"
WarpMeshFile    "warp.map" 
}

What am I doing wrong?

Thanks

**Comment by levinli303** [comment] 2022-03-25 01:59
@ImmersiveTheatres  you should either use https://github.com/levinli303/CelestiaApp/releases or download from the Mac App Store. 1.6.2 has no support for this

**Comment by pdbourke** [comment] 2023-06-18 09:54
An update on this ... my current recommended approach to using any software that creates fisheye (Stellarium, Celestia...) is to use my new screen warping tool. It captures a region of the primary, warps it and presents on the secondary display. It wasn't so cool in the past but is more viable now with the resolution of retina displays. Details can be found here
http://paulbourke.net/dome/fishwarp/#screen
including some comments on configuring Stellarium so it opens correctly and in the same location.
