### ISSUE TITLE
Black square around the Sun

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#1409] opened 2022-09-01 14:31 UTC
![image](https://user-images.githubusercontent.com/1612688/187938312-b3bea32f-2fd3-4cc5-84e1-e1e50dea4cf7.png)

I was able to reproduce it with GTK frontend only.

Steps to reproduce: enable planet orbits, go to cel://Follow/Sol:Earth/2022-09-01T14:05:06.49829Z?x=MHL9zpmPEv///////////w&y=NP4T6lFEn////////////w&z=bE++EAGevP///////////w&ow=0.2696041&ox=0.61314183&oy=0.020633211&oz=0.7422567&fov=46.849846&ts=1.0&ltd=0&p=0&rf=136181183&nrf=255&lm=0&tsrc=0&ver=3

Maybe moving up & high will be required. Also depends on distance to the Sun. Much easier to reproduce with a small window:
![image](https://user-images.githubusercontent.com/1612688/187939905-42944c8a-0654-4845-b20b-3c4d47a33b39.png)
cel://Follow/Sol/2022-09-01T14:08:01.61868Z?x=AAB9QrTiPKgR&y=LCAzq32hzP///////////w&z=AIBlhuWIg9cG&ow=0.20013171&ox=0.54564375&oy=-0.145735&oz=0.8006132&select=Sol&fov=23.575752&ts=1.0&ltd=0&p=0&rf=136181183&nrf=191&lm=0&tsrc=0&ver=3

**Comment by TheLostProbe** [comment] 2022-09-02 00:18
i was able to fully confirm that this does indeed happen with planets. it also occurs around other stars. the bug is visible on planets with both the Fuzzy Points and Scaled Discs rendering options

cel://Follow/TOI-3207:TOI-3207.01/2022-09-02T00:09:44.82531Z?x=AOCydhdqsjP//////////w&y=AFCKtkxEtlb+/////////w&z=AABD6dmrQAoB&ow=-0.4358858&ox=0.41791612&oy=0.28216168&oz=-0.745476&select=TOI-3207:TOI-3207.01&fov=125.02859&ts=1&ltd=0&p=0&rf=138253747&nrf=255&lm=2048&tsrc=0&ver=3
![image](https://user-images.githubusercontent.com/67564416/188032635-f1d2d0a8-e511-4f2c-914a-a8f151bede05.png)
cel://Follow/TOI-3207:TOI-3207.01/2022-09-02T00:08:55.80747Z?x=AOCJS69fo8n//////////w&y=ALCs/MjZxlI&z=AGB+lABCRb4C&ow=-0.4311777&ox=0.009358624&oy=-0.06936029&oz=-0.8995484&select=TOI-3207:TOI-3207.01&fov=125.02859&ts=1&ltd=0&p=0&rf=138253747&nrf=255&lm=2048&tsrc=0&ver=3
![image](https://user-images.githubusercontent.com/67564416/188032540-8496a3b8-d85d-4b74-aff5-62d93e7765e9.png)

**Comment by TheLostProbe** [comment] 2022-09-06 10:48
i have confirmed that it happens with moons, but only under Scaled Discs mode
![image](https://user-images.githubusercontent.com/67564416/188616405-cc09279c-012f-433b-8eb4-6222d9f1da99.png)

**Comment by TheLostProbe** [comment] 2022-09-08 08:30
oh god, its getting worse...
it affects stars in the vicinity of nebula models now. it appears to flicker when zooming in and out and orbiting the camera around
[this](https://celestia.mobi/resources/item?item=62C65394-8B0B-C5A7-B75C-DC1C68DEB834) addon is required for the Cel://URLs to work

cel://Follow/NGC2237/2022-09-08T10:22:28.16962Z?x=AAAAANiTPPB03b4&y=AAAAAAAqS0ACWnX7/////w&z=AAAAAIAznp7VCrgC&ow=0.8684787&ox=-0.48982716&oy=-0.07583937&oz=-0.007906457&select=NGC2237&fov=30.375284&ts=1&ltd=0&p=0&rf=138204563&nrf=255&lm=2048&tsrc=0&ver=3
![image](https://user-images.githubusercontent.com/67564416/189074251-15acf90a-ef2a-433a-a598-2f264b12be67.png)

it is also visible when zooming in

cel://Follow/NGC2237/2022-09-08T10:19:07.20068Z?x=AAAAAACUBn3viar3/////w&y=AAAAAABKuOgc0KYz&z=AAAAAABILdgi5NaU&ow=0.9856167&ox=0.16648185&oy=0.02404564&oz=-0.016290106&select=NGC2237&fov=7.028166&ts=1&ltd=0&p=0&rf=138204563&nrf=255&lm=2048&tsrc=0&ver=3
![image](https://user-images.githubusercontent.com/67564416/189073481-c3aab9e4-6a27-4770-a634-8f40455fcd3e.png)

Fuzzy Points is also affected

cel://Follow/NGC2237/2022-09-08T10:21:51.22317Z?x=AAAAAGiJfVEgLyg&y=AAAAAIBdeKY8G7n1/////w&z=AAAAAEC46cXvNrkE&ow=0.8418962&ox=-0.5395627&oy=-0.009023483&oz=0.0012202401&select=NGC2237&fov=30.375284&ts=1&ltd=0&p=0&rf=138204563&nrf=255&lm=2048&tsrc=0&ver=3
![image](https://user-images.githubusercontent.com/67564416/189074081-42834a24-7455-4eec-a60d-e1e290ca0fe3.png)

**Comment by TheLostProbe** [comment] 2022-09-08 08:37
wow this bug is beyond insane, just look at this!

cel://Follow/NGC2237/2022-09-08T10:28:33.11079Z?x=AAAAAMD1ImW6mR35/////w&y=AAAAAAAnnmgEgH7u/////w&z=AAAAAADemCQ6XVDT/////w&ow=0.12621187&ox=-0.8580762&oy=-0.47385523&oz=0.15243697&select=NGC2237&fov=30.375284&ts=1&ltd=0&p=0&rf=137942419&nrf=255&lm=2048&tsrc=0&ver=3
![image](https://user-images.githubusercontent.com/67564416/189075933-fcab86e4-3292-4426-b114-be753e95f0bd.png)

depth sorting issues are occurring too

cel://Follow/NGC2237/2022-09-08T10:29:33.48194Z?x=AAAAACAQTBfUCTD+/////w&y=AAAAAHBxR+OjisA&z=AAAAAEedjOLrWho&ow=0.3535039&ox=-0.20803428&oy=0.695492&oz=0.58995557&select=NGC2237&fov=30.375284&ts=1&ltd=0&p=0&rf=137942419&nrf=255&lm=2048&tsrc=0&ver=3
![image](https://user-images.githubusercontent.com/67564416/189076051-697cfe9c-a588-494e-a97d-8456f6593668.png)

**Comment by levinli303** [comment] 2022-09-08 13:32
I have been unable able to repro on iOS, Mac(GL or ANGLE+Metal). if you are on windows 10/11, you can also try to use the UWP version https://celestia.mobi/download/uwp.html to test.

**Comment by TheLostProbe** [comment] 2022-09-09 06:41
well, i have seen a few unrelated problems in the UWP version, but i will make issues for them later. the focus of this issue is black squares around stars, and not anything else.

it doesnt look like the UWP version has the issue, at least for stars. as for planets though...
cel://Follow/Sol:Earth/2022-09-09T06:38:42.14279Z?x=AA5fdg0Zbzk&y=ADOgu5wAywU&z=wBnMAUQ2IAQ&ow=0.6814089&ox=-0.006964908&oy=-0.72724324&oz=-0.08216254&select=Sol:Earth&fov=29.356295&ts=1&ltd=0&p=0&rf=205428663&nrf=255&lm=2048&tsrc=0&ver=3
![image](https://user-images.githubusercontent.com/67564416/189286927-ea8ec37d-8688-4e2a-a56d-20dd1e49e1d5.png)

however, turning up the mag limit makes it look like there isnt a black square around the planets, but instead a transparent square that renders in front of the orbits but behind the stars?
cel://Follow/Sol:Earth/2022-09-09T06:40:57.89695Z?x=AOZgXP3b5iY&y=wPdzf6d77AM&z=IPzWpp9nywI&ow=0.6814089&ox=-0.006964908&oy=-0.72724324&oz=-0.08216254&select=Sol:Earth&fov=29.356295&ts=1&ltd=0&p=0&rf=205428663&nrf=255&lm=2048&tsrc=0&ver=3
![image](https://user-images.githubusercontent.com/67564416/189287309-9ecbdc63-5803-4962-9ffe-6b8cbfc9ab63.png)

i will see later if i can access a macOS device and test, perhaps also an iOS device

**Comment by levinli303** [comment] 2022-09-09 07:27
I fail to see what is wrong in the screenshots the UWP build on the store does not include recent changes in celestia repo.

for iOS, please use TestFlight build instead of AppStore as the TestFlight build is up to date https://celestia.mobi/download/testflight.html

for Mac try https://dev.azure.com/CelestiaProject/Celestia/_build/results?buildId=1868&view=artifacts&pathAsName=false&type=publishedArtifacts either macosx-developerID-metalAngle/macosx-developerID-openGL

 I would actually recommend focusing on one platform, getting history builds to see on what date in this repo this starts occurring.

**Comment by TheLostProbe** [comment] 2022-09-09 08:40
sorry, i shouldve highlighted the problems in the screenshots. my bad!
![image](https://user-images.githubusercontent.com/67564416/189306016-a064111c-ef03-4f2c-9b6c-f608ebab2687.png)
![image](https://user-images.githubusercontent.com/67564416/189306081-03025b86-e4c9-448c-8f2d-71be38ab2ea8.png)

**Comment by levinli303** [comment] 2022-09-09 10:37
@TheLostProbe  this might be https://github.com/CelestiaProject/Celestia/issues/1414

**Comment by TheLostProbe** [comment] 2022-09-09 23:31
maybe, but zooming in or out makes the problem go away, it only happens at a very specific angle and distance

**Comment by TheLostProbe** [comment] 2022-09-14 01:03
@375gnu looks like it occurs on Qt as well

cel://Follow/Sol:Earth/2022-09-14T01:03:36.66367Z?x=qFq+ZaaewQ&y=A6MDegZPCw&z=IBCopm84zQ&ow=0.8622763&ox=-0.016966807&oy=-0.49758482&oz=-0.09274156&select=Sol:Earth&fov=29.214388&ts=1&ltd=0&p=0&rf=136370099&nrf=255&lm=14342&tsrc=0&ver=3
![image](https://user-images.githubusercontent.com/67564416/190035508-9551e74b-df9d-4d5f-8ed0-2828e8104c17.png)

**Comment by levinli303** [comment] 2022-09-14 12:37
> maybe, but zooming in or out makes the problem go away, it only happens at a very specific angle and distance

this is expected with the issue #1414

**Comment by TheLostProbe** [comment] 2022-09-23 08:44
now there are 2 black boxes around the stars

cel://Follow/Sol:Earth/2010-08-12T13:44:31.91561Z?x=AAAAAOcdUgquMun//////w&y=AAAAACbbEPf/Odb//////w&z=AAAAAAiY96wrLtL//////w&ow=0.7524634&ox=0.07473861&oy=-0.29202974&oz=-0.5856036&fov=69.448135&ts=1&ltd=0&p=0&rf=134862215&nrf=255&lm=4&tsrc=0&ver=3
![image](https://user-images.githubusercontent.com/67564416/191923868-5953c3c6-e47f-4a43-8cba-f95d47c84549.png)

**Comment by TheLostProbe** [comment] 2022-10-23 21:39
this error has been fixed by #1446

**Closed** 2022-10-24 07:44 UTC
Labels: bug, renderer
