### ISSUE TITLE
Rings have a portion sliced away [1.7.0]

### ISSUE THREAD

**Issue by TheLostProbe** [CelestiaProject/Celestia#1400] opened 2022-08-19 23:22 UTC
recently ive noticed that sometimes a strange bug occurs where a portion of a planets rings are "sliced away". it only happens on certain planets, at certain angles, and certain distances. im not entirely certain which commit has caused it, but its been happening since at least #1394. since i can not seem to replicate the bug in the solar system, i will give you a link to download the planet in the screenshots: https://drive.google.com/file/d/1dGls5Znj638w_s_rILkF0BBT6EsOevfQ/view?usp=sharing

and heres a cel://URL:
cel://Follow/Jaxeltheia:Seranna/2022-08-19T23:10:52.56992Z?x=ADWw6B8fee3//////////w&y=wJHExqNmVgU&z=wLZVlomuaAU&ow=0.76993096&ox=0.011826935&oy=0.6039904&oz=0.2055775&select=Jaxeltheia:Seranna&fov=30.375294&ts=1&ltd=0&p=0&rf=138205075&nrf=247&lm=2048&tsrc=0&ver=3

**To Reproduce**

1. use the cel://URL i linked before to visit the planet that i noticed the bug on
2. rotate the camera around a bit if the bug isnt visible (dont need to if the bug _is_ visible)
3. see error

**Expected behavior**
the ring system should be rendered in full, not with a section cut away

**Screenshots**
![image](https://user-images.githubusercontent.com/67564416/185716273-b2b4407a-9173-487f-87d5-ef6d0ba3c2a5.png)
![image](https://user-images.githubusercontent.com/67564416/185716294-b9a0ff06-5cfc-451c-ac6f-bc6a7330348b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 21H2 build 19044.1889 64-bit
 - Frontend: native win
 - Version: 1.7.0 (fourth-latest build from **Actions** tab)

**Comment by levinli303** [comment] 2022-08-20 01:34
the add-on and URL appear to be not working <img width="574" alt="Screen Shot 2022-08-20 at 09 31 05" src="https://user-images.githubusercontent.com/17924287/185724133-985ddb33-1f2c-4cef-bdfe-62caca9fb1d2.png">

**Comment by TheLostProbe** [comment] 2022-08-20 04:32
forgot to add the stc file for the star into the zip. ive updated the original post with a version that will work this time

**Comment by 375gnu** [comment] 2022-08-23 10:04
That's weird, but #1394 really is to blame.

**Comment by levinli303** [comment] 2022-08-30 12:33
<img width="1026" alt="Screen Shot 2022-08-30 at 20 32 21" src="https://user-images.githubusercontent.com/17924287/187437444-3d851ec6-0b72-42d7-ab55-2afc0e390f50.png">

seeing z/w > 1 for the sliced away part.

**Comment by 375gnu** [comment] 2022-08-30 14:10
I've the root cause why this happens. The code to merge depth partitions assumes that all partitions go one by one in sorted order but this is not the case for systems with several suns.

**Comment by 375gnu** [comment] 2022-09-01 09:30
fixed with #1404

**Closed by 375gnu** 2022-09-01 09:30 UTC
Labels: bug
