### ISSUE TITLE
Missing licence file

### ISSUE THREAD

**Issue by ghost** [CelestiaProject/Celestia#1389] opened 2022-07-31 20:37 UTC
**Describe the bug**
The license button is unable to open file copying due to improper installation

![image](https://user-images.githubusercontent.com/94876428/182044356-e05d67b2-1e2f-45a4-a740-f97fce9ece99.png)

**To Reproduce**
1. Go to 'Help'
2. Click on 'About'
3. Scroll down to 'License'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. GNU/Linux, Windows, macOS] Linux Mint 20.3
 - Frontend: [e.g. Qt, native Win, native Mac]  GTK+ Front End
 - Version: [e.g. 1.7.0] 1.6.1

**Additional context**

**Comment by 375gnu** [comment] 2022-08-01 07:10
@natewrench where you installed Celestia from?

**Comment by natewrench** [comment] 2022-08-01 11:49
> @natewrench where you installed Celestia from?

celestia.space

**Comment by 375gnu** [comment] 2022-08-01 12:08
@natewrench don't close, as the packages came from celestia.space then we should fix them.

**Comment by dave-kaye** [comment] 2022-09-09 19:03
Placed a proposed fix in the pull requests.

**Comment by dave-kaye** [comment] 2022-10-20 20:20
Commit 6863d44 fixed this issue.  @375gnu please close this issue.

**Comment by dave-kaye** [comment] 2022-10-21 15:05
Commit 6873d44 fixed this issue on 1.7.0, - recent compile works.

Downloaded 1.6.2.2 source rpm from munix9 and compiled it.  It also works.   Version 1.6.1 is very old but seems that it should also work.  Appears that problem is probably in Mint Linux, and the version quoted is also old.

I think the issue is resolved and can be closed.

**Comment by dave-kaye** [comment] 2023-01-03 21:52
@375gnu or @levinli303 please mark this issue #1389 as corrected and remove it from the list.  I have downloaded and installed the patched 1.7.0 development GIT 12/24/22 code and it works for the GTK About -> license, using my own Linux installation which uses the Cmake file supplied with Celestia.  I have also made a new openSUSE Tumbleweed installation and used munix9 Tumbleweed rpms from the 1.7.0 Celestia 12/4/22 GIT version.  They move the license file to a special directory as practiced by openSUSE.  But the corrected code made a copy of the license file in the location needed by GTK and munix9's version worked as well.  Therefore the issue appears to be resolved in the presently being developed code. 

Using munix9 rpms I compiled Celestia 1.6.2.2 GTK and About -> license is working without the need for an error correction.  Once again, munix9 moves the license file to a special directory as practiced by openSUSE.  But the install files keep a copy of the license file in the location needed by GTK.

I am unable to compile Celestia GTK 1.6.1 due to old automake and autoconfig files.  However, the make files show that the license file is being installed to the same directory and the code for the GTK about box is the same for versions 1.6.2.2 and 1.6.1, so it should be working as well.

The issue is for Linux Mint 20.3 using Celestia 1.6.1. 375gnu stated that celestia.space should be corrected.  But no direct link to 1.6.1 exists on the download page for Linux - only links to Windows and MacOS versions.  Both Windows and MacOS have interface code ported to their system, and do not use GTK.  Links to Linux versions are from a repository maintained by @munix9, and there the versions found are 1.6.2.2 and 1.7.0.

It would not appear that celestia.space needs to be corrected.  The user probably got a version 1.6.1 a while ago from celestia.space and is still using it.

**Comment by 375gnu** [comment] 2023-12-22 20:20
Fixed in 1.6.4-2 available from https://celestiaproject.space/deb.html / https://celestiaproject.space/ubnt.html

**Closed by 375gnu** 2023-12-22 20:20 UTC
Labels: packaging
