### ISSUE TITLE
Point rendering is not working correctly

### ISSUE THREAD

**Issue by levinli303** [CelestiaProject/Celestia#1339] opened 2022-01-29 05:10 UTC
**Describe the bug**
it seems halo is being drawn incorrectly, see screenshot centered on Sun

**To Reproduce**
1. Go to 'Sun'

**Screenshots**
<img width="473" alt="Screen Shot 2022-01-29 at 1 06 29 PM" src="https://user-images.githubusercontent.com/17924287/151648194-434bd563-e91c-4421-9b8d-57226b4678c7.png">

**Desktop (please complete the following information):**
 - OS: Android
 - Frontend: Android

**Additional context**
Might be from #1321

**Comment by 375gnu** [comment] 2022-01-29 08:42
It looks like "scaled disks" starfield mode is on. This issue exists since the very old time. And the root cause is that in this mode galo size is calculated differently.

**Comment by levinli303** [comment] 2022-01-29 09:11
@375gnu 

the screenshot is from fuzzy point mode

https://user-images.githubusercontent.com/17924287/151655181-2206c22a-c4fc-4273-b7a6-43e859bd064f.mov

**Comment by levinli303** [comment] 2022-01-29 09:14
and the halo is disappearing as soon as the center of sun is off screen (before then, it only disappears when the entire disc of sun goes off screen)

https://user-images.githubusercontent.com/17924287/151655235-d4a9a018-8355-4ff2-b64a-f05e05b3c330.mov

**Comment by 375gnu** [comment] 2022-01-29 19:54
@levinli303 could you describe what's wrong with the 1st video? regarding the 2nd - i'm unable to reproduce it.

**Comment by SevenSpheres** [comment] 2022-01-29 23:10
> @levinli303 could you describe what's wrong with the 1st video? regarding the 2nd - i'm unable to reproduce it.

The Sun's central "glow" is missing, making it appear too dark. This same issue appeared and was fixed before (#541). Although this issue has always existed and never been fixed in "scaled disks" mode, so I'm not sure why the original issue was closed.

**Comment by 375gnu** [comment] 2022-01-30 08:34
afair some GL ES environments have too small points so you introduced renderLargePoint, which is still called: https://github.com/CelestiaProject/Celestia/blob/master/src/celengine/render.cpp#L1829 https://github.com/CelestiaProject/Celestia/blob/master/src/celengine/render.cpp#L1849 and it itself doesn't have any changes.

**Comment by levinli303** [comment] 2022-01-30 08:41
this is reproduced on an emulator where max point is 8192. You should also be able to reproduce by zooming out until the star is rendered with point instead of square in renderLargePoint.

The issue occurs because when point is used to render glow, we used to draw the point at the surface of the star (as you can see in the calculateCenter function), but now we are drawing the glow at the center of the star.

**Closed** 2022-01-31 09:20 UTC
