### ISSUE TITLE
black screen on Wayland/Sway, with QT5

### ISSUE THREAD

**Issue by swordhui** [CelestiaProject/Celestia#850] opened 2020-10-10 04:33 UTC
**Describe the bug**
I compiled Celestia from source code on my linux system which runing wayland/sway. the main window showed up but nothing is rendered. it's same with or without -DENABLE_GLES=ON.

**To Reproduce**

1. install wayland/wlroots/sway
2. install qt5 with wayland support
3. compile Celestia with -DENABLE_GLES=ON
4. run celestia-qt5 on wayland/sway

**Expected behavior**

**Screenshots**
![3c31100bebcb4d918c05b626ef8e0b4](https://user-images.githubusercontent.com/243104/95645747-c0ed3080-0af4-11eb-9b76-25a017b66f0a.jpg)
![9cbe748151fe8fcd600bcef67c639fc](https://user-images.githubusercontent.com/243104/95645750-c9de0200-0af4-11eb-860e-ac915cbc7b20.jpg)
![0cfd4d1d6fcf1c11173f5d127aff57c](https://user-images.githubusercontent.com/243104/95645754-ccd8f280-0af4-11eb-9872-ae32e8f89d44.jpg)
![a43ac6ea60834cd2f127a55ea235d4a](https://user-images.githubusercontent.com/243104/95645755-cf3b4c80-0af4-11eb-8517-a73aae2fff2d.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. GNU/Linux, Windows, macOS]
 - Frontend: [e.g. Qt, native Win, native Mac]
 - Version: [e.g. 1.7.0]

**Additional context**

**Comment by 375gnu** [comment] 2020-10-10 12:28
i think the problem is with legacy GL widget, unfortunately recommended to use one has a lot of issues in fullscreen mode.

**Comment by 375gnu** [comment] 2022-10-25 21:06
@swordhui for quite a while we use QOpenGLWidget which should work in OpenGL ES mode and so it should be compatible with Wayland. Could you check?

**Comment by 375gnu** [comment] 2023-01-15 10:29
it seems that wayland is working now, sop closing this

**Closed by 375gnu** 2023-01-15 10:29 UTC
Labels: bug, help wanted, qt, awaiting response
