### ISSUE TITLE
Render bug with over-unity stellar semi-axes

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#589] opened 2020-01-19 17:12 UTC
In any very close binary star system, the stars are rendered with dark circles on them. Example:

![closebinarybug](https://user-images.githubusercontent.com/56284207/72685102-fb64f800-3aa3-11ea-8346-b0dec87b233a.png)

The latest 1.7 builds don't have this bug because stars appear dark all over. If this was an attempt to fix the bug it didn't work very well...

**Comment by 375gnu** [comment] 2020-01-19 19:40
@SevenSpheres where did you take those stars? i can't reproduce the issue cause default data doesn't have them.

**Comment by SevenSpheres** [comment] 2020-01-19 20:05
http://celestiamotherlode.net/catalog/show_addon_details.php?addon_id=1672

**Comment by 375gnu** [comment] 2020-01-19 21:49
Not reproducible. Please check your extras.
For the future: always provide test data set & URL otherwise bugreport will be rejected.

**Comment by SevenSpheres** [comment] 2020-01-19 23:36
> Not reproducible. Please check your extras.

Try this URL with 1.6.x or older 1.7 builds:

cel://Follow/HR%205171/2020-01-19T23:35:56.58236?x=AAAgQyTavhxD/f///////w&y=AADQfHEbE+Qy&z=AACEPtG4JsBv&ow=-0.682174&ox=0.244209&oy=-0.601529&oz=-0.336398&select=HR%205171&fov=25.5297&ts=1&ltd=0&p=0&rf=1890199&lm=128&tsrc=0&ver=3

You are correct that it's not reproducible with the latest 1.7 builds. As I said:

> The latest 1.7 builds don't have this bug because stars appear dark all over. If this was an attempt to fix the bug it didn't work very well...

**Comment by SevenSpheres** [comment] 2020-01-30 23:22
I'm seeing this same problem with Dschubba B, which I've modified to have the correct oblateness. However, I don't see it with any other oblate stars. Very strange...

![dschubbabug](https://user-images.githubusercontent.com/56284207/73499202-b5017a00-437c-11ea-91ef-4316477c1857.png)

**Comment by SevenSpheres** [comment] 2020-01-30 23:38
_I figured it out I figured it out!_ It has nothing to do with close binaries. All of these stars (HR 5171 AB, HD 226868 A, Dschubba B) have a semi-axis value greater than 1. That must be what's causing it!

**Comment by 375gnu** [comment] 2020-01-31 13:43
Dow you have it with the latest 1.7 builds?

**Comment by SevenSpheres** [comment] 2020-01-31 22:03
> Dow you have it with the latest 1.7 builds?

No, as I've said twice now, in the latest 1.7 builds all stars look like this:

![darksunbug](https://user-images.githubusercontent.com/56284207/73577678-c9a44780-443a-11ea-9e92-4e1557da7a71.png)

**Comment by 375gnu** [comment] 2020-02-01 08:57
> No, as I've said twice now, in the latest 1.7 builds all stars look like this:

And that's the first time you show the picture.

It seams that the texture used is not a default one. What do you have with default textures?

Regarding the original issue - as it doesn't present in 1.7, we can either document it, throw warnings if  `SemiAxes` has values > 1, or normalize them (and pray that no other issue caused by this change).

**Comment by SevenSpheres** [comment] 2020-02-01 17:16
The texture is FarGetaNik's. With default textures it's similar - i.e., too dark.

The original issue _was_ present in 1.7 until the most recent builds, which broke something with the star rendering. Should I make a separate issue for that?

**Comment by 375gnu** [comment] 2020-02-01 17:43
> With default textures it's similar - i.e., too dark.

Please provide it. I don't have any issues with colours.

> Should I make a separate issue for that?

Yes. Don't unrelated issue reports to report problems.

**Comment by Anthony-B-Russo10** [comment] 2020-02-01 17:52
Yes you should.

**Comment by SevenSpheres** [comment] 2020-02-07 22:48
Noting that with the semi-axes changed on HR 5171, the bug is indeed fixed, but there's still some flickering.

**Comment by 375gnu** [comment] 2020-02-14 21:44
Taking in to account that:
1) current 1.7 doesn't have the bug
2) 1.6 code is quite different as it uses ancient OpenGL here
3) workaround with rejection of incorrect semi axes values is not accepted by community
closing as "won't fix"

**Closed by 375gnu** 2020-02-14 21:44 UTC
