### ISSUE TITLE
[1.6.2] Solar System Browser planet names are in gibberish

### ISSUE THREAD

**Issue by RacerBG** [CelestiaProject/Celestia#875] opened 2020-11-20 15:46 UTC
**Describe the bug**
The names of the planets in the Bulgarian language (I guess the bug will be the same in Russian too) are in gibberish instead of Bulgarian.

**To Reproduce**
1. Use the Bulgarian language (as I wrote _I think_ Russian will be affected too).
2. Open the Solar System Browser.

**Expected behavior**
The names of the planets should be in their native language.

**Screenshots**
![bug](https://user-images.githubusercontent.com/68707872/99819345-05d69f00-2b58-11eb-8222-72c34f8ad7df.png)

**Desktop (please complete the following information):**
 - Windows 7 SP1 x64
 - Frontend: Native
 - Version: 1.6.2 Final

I haven't noticed other other instances of this bug. I believe that this is a Unicode problem.

**Comment by levinli303** [comment] 2020-11-20 15:52
this is known, fixed in 1.7.0, but the backport https://github.com/CelestiaProject/Celestia/pull/784 does not work, and we have no idea why it does not work.

**Comment by 375gnu** [comment] 2020-11-20 15:53
As #322 states we don't have any windows developer. I'm unabe to reproduce this bug under wine.

**Comment by RacerBG** [comment] 2020-11-20 15:56
> 
> 
> As #322 states we don't have any windows developer. I'm unabe to reproduce this bug under wine.

I'm not a developer either but is there any way to help as a Windows user myself?

**Comment by levinli303** [comment] 2020-11-20 17:03
it seems we cannot use ListView_InsertColumn and some other methods, since their ANSI version does not support unicode

**Comment by 375gnu** [comment] 2020-11-23 19:14
@RacerBG @Askaniy please test https://celestia.space/files/celestia/celestia-1.6.2.1.7z

**Comment by Askaniy** [comment] 2020-11-24 10:42
@375gnu
- It fixed the names
- It broke sharpness on the system scale not 100%
![image](https://user-images.githubusercontent.com/44873271/100083222-33725f80-2e5a-11eb-98c7-e67aba92009c.png)

**Comment by 375gnu** [comment] 2020-11-24 11:07
> It broke sharpness on the system scale not 100%

this fix doesn't contain any font rendering changes. are you sure that it was sharp before?

**Comment by levinli303** [comment] 2020-11-24 15:47
on my win10 vm with 300% scaling, there was no change with scaling. was blurry, still blurry.

**Closed** 2020-11-26 13:00 UTC
Labels: bug, help wanted, high priority, native win, windows

**Comment by Askaniy** [comment] 2020-11-26 19:55
@375gnu I re-downloaded 1.6.2 and 1.6.2.1, installed them clean. Both are blurred, the update corrects the inscriptions. Apparently the last time 1.6.2 was launched with normal sharpness because of the path known to the system, where I could do some magic.
![image](https://user-images.githubusercontent.com/44873271/100388019-84d94500-303a-11eb-8565-f7923d5e4fe8.png)
